[[constraint]]
  name = "github.com/maruel/panicparse"
  branch = "master"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mitchellh/go-wordwrap"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
